const FETCH_ITEMS_SUCCESS = `FETCH_ITEMS_SUCCESS`;
const FETCH_ITEMS_REQUEST = `FETCH_ITEMS_REQUEST`;
const FETCH_ITEMS_ERROR = `FETCH_ITEMS_ERROR`;
const ITEM_ADDED_TO_CART = `ITEM_ADDED_TO_CART`;
const ITEM_REMOVED_FROM_CART = `ITEM_REMOVED_FROM_CART`;
const ITEMS_REMOVED_FROM_CART = `ITEMS_REMOVED_FROM_CART`;
const CLEAR_CART = `CLEAR_CART`;
const PRODUCT_ADDED_TO_LIST = `PRODUCT_ADDED_TO_LIST`;
const SHOW_ALERT = `SHOW_ALERT`;
const HIDE_ALERT = `HIDE_ALERT`;

export {
    FETCH_ITEMS_SUCCESS,
    FETCH_ITEMS_REQUEST,
    FETCH_ITEMS_ERROR,
    ITEM_ADDED_TO_CART,
    ITEM_REMOVED_FROM_CART,
    ITEMS_REMOVED_FROM_CART,
    CLEAR_CART,
    PRODUCT_ADDED_TO_LIST,
    SHOW_ALERT,
    HIDE_ALERT
}